export type GameScreen =
  | "menu"
  | "create"
  | "career"
  | "offers"
  | "season"
  | "vct"
  | "recap"
  | "vctRecap"
  | "profile"
  | "market"
  | "vctOffseason"
  | "leaderboard"
  | "coachSelect"
  | "coachDashboard"
  | "coachRoster"
  | "coachMarket"
  | "coachTactics"
  | "coachMapPool"
  | "coachMapVeto"
  | "coachSeason"
  | "coachEventRecap"
  | "coachOffseasonRecap"
  | "coachMidseasonRecap"
  |"coachTransferNegotiation"
  |"coachJobMarket"
  |"coachProfile";
export type ProfileReturnScreen = "career"|"season"|"vct"|"recap"|"vctRecap";
export type MarketWindow = "midseason"|"offseason"|null;